# Repairing and tuning the Whisper with 3D printed parts
![3D printing](whisperfoilingcatamaranreplacementwand.png)

* [__wand system__](#Wand-System) to replace parts that break with easier access as well as tunings
* [__rudder holder__](#Rudder-Holder) to lock in various heights in shallow waters
* [__speedpuck mount__](#Speedpuck-Mount)

# Wand System
The [Whisper foiling catamaran](https://www.youtube.com/channel/UCwhb6u4A_Hy-c-eJbMLW7bg) uses "wands" as ride height sensor to dynamically control the foil lift. Parts of that wand system break from time to time, so printing them yourself can be convenient.


To produce an entire wand, you do need:
--------------------------------------------------------
* carbon rod (CFK) 8mm diameter, 1m length (you will need to cut it to 830mm length)

* 3D print paddle (lower end)
* 3D print arm (top part of wand)
* 2 stainless screws (3mm x 10mm or longer) -- you will clip to proper length anyway

Print material needs to be stronger than PLA, so I use e.g. ASA instead..


additional replacement parts related to the wand system:
--------------------------------
* lever inside of foil ride height mechanism
 

Updates:
----------------------
* 20180826: updated wand arm to mount the rod screw from the side
* 20200530: added wand paddle/skimmer model with screw mounting from aft
* 20200530: added wand paddle/skimmer model with screw mounting side - maybe thats the most convenient option for mounting. 
* 20200606: added wand arm version to mount the rod screw from aft, and another version to mount the screw from both sides, to make unmount/mounting easier. mechanically is the version from 2018 with one rod screw from side more robust.

wand arm:
===========
* use 8mm drill to create a snug fit of the rod into the 3D printed parts
* drill 5mm hole for the shock cord that pulls the arm back
* drill 4mm hole for the hinge
* drill 2.5mm holes for the metal connector, and cut a M3 3mm metric thread into it 
* drill a 2.5mm hole into the carbon rod for the 3mm screw (I use a HSS-cobalt drill for the Carbon rod)
* clip the screw to a length so it just doesnt stand out on the other side of the arm

wand paddle:
===========
* use 8mm drill to create a snug fit of the rod into the 3D printed parts
* drill a 2.5mm hole for the 3mm screw (I use a HSS-cobalt drill for the Carbon rod)
* clip the screw to a length so it just doesnt stand out on the other side of the paddle

wand rod:
=============
* total length of original wand including arm and paddle is 930mm
* cut the carbon rod to 830mm 

wand ride height lever:
===========
* drill 2.5mm holes for the 3mm screws (I use a HSS-cobalt drill for the Carbon rod)
* drill 2.5mm holes for the connecting rod
* cut M3 3mm metric thread into it -- you might use only 2 of three cutting tools, so that the fit of the screw is tighter
* a tiny bit of glue helps additionally to lock the screws, so they dont open accidentally 


## 3D models
you can download from Fusion 360 site  in a format of your choice

* [wand paddle](https://a360.co/2O1Cxfj)
* [wand arm](https://a360.co/2wckjRI)
* [wand ride height lever](https://a360.co/2w9MqAS) 



# Rudder Holder




# Speedpuck Mount

# License
All models are licensed under __Creative Commons - Attribution - Non Commercial - Share Alike__